name: heart.racing
favicon: null
layout_spectrum: 0.23080779681913555
typography_spectrum: 0.05075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#e80185'
    - '#ed5627'
    - '#000000'
    - '#01a7d7'
  brandStrength: 0.875
  lightness: 0.8367784337606281
  saturation: 0.5063188925851136
  rhythmicContrast: 0.16638861899264157
purpose: []
