name: heart.racing
favicon: null
layout_spectrum: 0.23080779681913555
typography_spectrum: 0.7036876273341477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3051429013721645
  lightness: 0.8367784337606281
  saturation: 0.5063188925851136
  rhythmicContrast: 0.16638861899264157
purpose: []
